### ISSUE TITLE
nginx config for tunnel.berlin.freifunk.net not found

### ISSUE THREAD

**Issue by pmelange** [freifunk-berlin/puppet-files#7]
The config files in /etc/nginx on tunnel.berlin.freifunk.net were mysteriously deleted.  After rerunning puppet, all the sites-enabled and sites-active config files have been recreated except for tunnel.berlin.freifunk.net.

@SvenRoederer do you have a copy of this file somewhere?  Can you add this to the puppet configuration?  Is it already somewhere which is not entirely obvious (master branch)?

**Comment by pmelange** [comment]
Why is the file gone....

Irgendwann in 2014 hat jemand das debian packet nginx-common auf "purge" getsettet.  Wenn das packet nginx installiert ist, macht der debian package manager wieder ein purge.

Letze update von nginx war in Jan.  Aber den letzen neustart ist erst am anfang Mrz passiert.  Alle configs würde getroffen.

Jetzt sind alle configs von puppet wieder hergestellt, aber tunnel.berlin.freifunk.net ist nicht in der repo.

nginx-common ist auch jetzt auf "Hold" gesettet.

**Comment by SvenRoederer** [comment]
* Warum wurde denn das Paket gelöscht? Und damit auch die Konfigs?
* Wenn das Paket auf "Hold" steht, werden doch auch keine updates installiert? Ist das sinnvoll, insb. für Security-Updates.

**Comment by pmelange** [comment]
Why is the file gone....

Sometime in 2014 someone set the debian package to "purge".  Whe the package nginx is installed/updated, the debian package manager purges the nginx-common files again.  All the config files were affected.

The last update of nginx was in Jan 2019.  But the last time nginx restarted was in March. 

Now all the config have been regenerated from puppet, but tunnel.berlin.freifunk.net is not in the repo.

nginx-common is now set to "hold".

**Comment by pmelange** [comment]
Read carefully.  There is a difference between nginx and nginx-common.

**Comment by pmelange** [comment]
The update was done with aptitude.  I never use it.  Maybe it goes through the list on packages and always repurges them.  Maybe it's dpkg itself purging the files automatically

**Comment by pmelange** [comment]
@booo said it has also happened in the past.  Nobody understood why.  

It seems like it is the same reason that buildbot was down recently.  I don't have access to buildbot.  I don't know if anyone put the nginx-common package there to "hold" (it might also be ok to set it to "remove" which doesn't erase config files).

**Comment by SvenRoederer** [comment]
The default policy of apt* is erase, but keep configs, so normally a reinstall or upgrade will not break anything. But I'm not aware what puppet is doing ....

**Comment by booo** [comment]
As far as I know nobody executed puppet. The change is not an immediate result of a puppet run.

Maybe the puppet configuration create a strange package configuration or the apt source we use for nginx has done something strange (deb http://nginx.org/packages/ubuntu trusty nginx)?

Should we recreate the tunnel and ca configuration or should we create a redirect to a e.g. wiki page?

**Comment by SvenRoederer** [comment]
We should recreate the tunnel.berlin. -CA, as long as we offer the tunnels.
But for ca. we should redirect to the VPN03-page of the wiki

**Comment by booo** [comment]
With https://lists.berlin.freifunk.net/pipermail/berlin/2019-March/039247.html we proposed the shutdown of the CAs. I suggest that we follow throw with this now and redirect all related subdomains to a proper description of the current tunnel setup.

**Comment by SvenRoederer** [comment]
A "service terminated" webpage is online. This page contains some links to Wiki-page VPN03 and Wiki-page tunnel-berlin (Tunneldigger).

https://tunnel.berlin.freifunk.net/ gives a bad cert-domain error (cert seems only for config.berlin.freifunk.net)
